apiVersion: v1
kind: Secret
metadata:
  name: ai-radar-secrets
  namespace: ai-radar
  annotations:
    # For integration with external secret management (e.g., Vault)
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ai-radar"
    vault.hashicorp.com/agent-pre-populate-only: "true"
type: Opaque
data:
  # Base64 encoded values - REPLACE THESE IN PRODUCTION
  postgres-password: YWlfcHdk  # ai_pwd
  minio-access-key: bWluaW8=   # minio
  minio-secret-key: bWluaW9fcHdk  # minio_pwd
  openai-api-key: eW91cl9vcGVuYWlfa2V5X2hlcmU=  # your_openai_key_here
  newsapi-key: eW91cl9uZXdzYXBpX2tleV9oZXJl  # your_newsapi_key_here
stringData:
  postgres-url: "postgresql://ai:ai_pwd@postgres:5432/ai_radar"
  nats-url: "nats://nats:4222"
---
